### ISSUE TITLE
cut_off_values_upper_lower_percentile

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#10]
@FabianIsensee Hi, sir. I find that in the function cut_off_values_upper_lower_percentile(image, mask=None, percentile_lower=0.2, percentile_upper=99.8), maybe res should be returned instead of returning image since  res = np.copy(image) is used. I am not sure since I am a novice. Is it this? Thank you!

**Comment by FabianIsensee** [comment]
You are correct. That is a mistake. Thanks for pointing that out!

**Comment by FabianIsensee** [comment]
It is fixed now =)

**Comment by yianzhongguo** [comment]
@FabianIsensee Thank you！
