### ISSUE TITLE
What the variable t1km_sum is

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#11]
@FabianIsensee Hi, sir. I am still perusing your code and have learned a lot. Now I do not make it clear what the variable t1km_sum is  in the dataset.py and what role does it play. Thank you!

**Comment by FabianIsensee** [comment]
When segmenting these images clinicians typically look at a subtraction image between t1 and t1c to better recognize the enhancing tumor parts. I experimented with using that in the network but it did not provide any benefits. The code is still there though (that input channel is not used by the network)

**Comment by yianzhongguo** [comment]
Got it, thank you!

**Comment by yianzhongguo** [comment]
Sorry, another question. In the line 179 of train_network.py: train_fn = theano.function([x_sym, seg_sym], [loss, acc_train, loss_vec], updates=updates), but in the line 238: loss_vec, acc, l = train_fn(data, seg). Maybe the losss_vec and loss location should be swapped, is it? Thank you!
