### ISSUE TITLE
How can it be transformed into dimension 5  in the line 139:"l = DimshuffleLayer(l, (0, 2, 3, 4, 1))" which seems to increace dimension batch

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#17]
@FabianIsensee Hi, sir. According to the line 130 :"l_pred = Conv3DLayer(l, num_output_classes, 1, pad='same', nonlinearity=None)" in the network_architecture.py, the output shape of the network should be 4*128*128*128 which is dimension 4. How can it be transformed into dimension 5  in the line 139:"l = DimshuffleLayer(l, (0, 2, 3, 4, 1))" which seems to increace dimension batch.  Thank you!

**Comment by FabianIsensee** [comment]
Network output is always 5D

batch, channel, X, Y, Z

**Comment by yianzhongguo** [comment]
But it seems that the output of l_pred = Conv3DLayer(l, num_output_classes, 1, pad='same', nonlinearity=None) is 4D.

**Comment by FabianIsensee** [comment]
it's 5D. Every conv3D layer has 5d inputs and outputs

**Comment by yianzhongguo** [comment]
I know the input of conv3D layer is 5D, but what does the shape of outputs is determined by?

**Comment by FabianIsensee** [comment]
by the batch size of the input, num_output_classes, padding, stride and input shape

the output here is is 5D with the same batch size and 3d shape of the input and num_output_classes channels

**Comment by yianzhongguo** [comment]
I've made it clear, thank you very much!
