### ISSUE TITLE
A question about the dice loss

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#18]
@FabianIsensee Hi, sir. As far as I know the labels in the dataset of brats 2017 are 0,1,2,4. But in the definition of the function  hard_dice_per_img_in_batch in the utils.py you use for i in range(n_classes): y_true_i = T.eq(y_true[b], i_val). Since n_classes is 4 i is in [0,1,2,3] which seems  to be inconsistent with the true labels. I do not know whether it is that. Thank you!

**Comment by FabianIsensee** [comment]
Please look in the code. Labels are converted to 0, 1, 2, 3 during preprocessing

**Comment by yianzhongguo** [comment]
Thank you！
