### ISSUE TITLE
Different data_gen_train in different eporchs

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#19]
@FabianIsensee Hi, sir. In the train_network.py  when the eporch==100 and epoch==175 the data_gen_train is different generated form create_data_gen_train with different parameters. Why this happend? Thank you!

**Comment by FabianIsensee** [comment]
Please read the paper carefully:
"Whenever possible, we initialize these techniques using aggressive parameters that we subsequently attenuate over the course of the training."
Data augmentation is made to be less aggressive at some point

**Comment by yianzhongguo** [comment]
Thank you！
