### ISSUE TITLE
ImportError: cannot import name downsample

### ISSUE THREAD

**Issue by pykao** [MIC-DKFZ/BraTS2017#2]
Hello,
Could you tell me what version of theano and lasagne you used?
I tried to run python train_network.py 0, and it gave me an error: ImportError: cannot import name downsample

My version theano is 1.0.1, and lasagne is 0.1.

Thank you,
Po-Yu

**Comment by pykao** [comment]
I upgraded my lasagne to 0.2.dev1 and it solved my problem. 
pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip

**Comment by FabianIsensee** [comment]
Glad you could solve the issue!
Regards,
Fabian
