### ISSUE TITLE
/batchgenerators/batchgenerators/augmentations/crop_and_pad_augmentations.py:140: UserWarning: Raause the crop along with the dasired margin does not fit the data. data: (1, 4, 160, 192, 160), crop_s4.0]   str(margins)))

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#20]
@FabianIsensee Hi, sir. When I trained the network the following warning emerged : /batchgenerators/batchgenerators/augmentations/crop_and_pad_augmentations.py:140: UserWarning: Raause the crop along with the dasired margin does not fit the data. data: (1, 4, 160, 192, 160), crop_s4.0]
  str(margins))). I am puzzled. Did you experience it?

**Comment by FabianIsensee** [comment]
please pull batchgenerators again and reinstall it with "pip install --upgrade ."

**Comment by yianzhongguo** [comment]
Thank you！

**Comment by yianzhongguo** [comment]
@FabianIsensee Hi, sir. Sorry,but it is not clear for me about "pull batchgenerators". I reinstall the batchgenerators with the command "pip install --upgrade batchgenerators" and the issue is still there.

**Comment by FabianIsensee** [comment]
I presume you got batchgenerators from our git repository? You need to get the most recent version by pulling from that git repo again. Go into the folder where the installation files are and type "git pull"

**Comment by yianzhongguo** [comment]
Thank you very much！
