### ISSUE TITLE
Can I accelerate the training course with GPU?

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#21]
@FabianIsensee Hi, sir. I am training the network of your code, but it is too slow as follows. Can I accelerate it with GPU? Thank you!

val dice:  [0.81688768 0.68206574 0.63964228 0.01935757]
This epoch took 19384.164900 sec

**Comment by FabianIsensee** [comment]
Of course!
http://deeplearning.net/software/theano_versions/dev/library/config.html

You need to set the device in theanorc
