### ISSUE TITLE
The patch size in the create_data_gen_train function

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#23]
@FabianIsensee Hi, sir. I find  you have set the patch_size=(160,192,160): "data_gen_train = BatchGenerator3D_random_sampling(patient_data_train, BATCH_SIZE, num_batches=None, seed=False,
                                                          patch_size=(160, 192, 160), convert_labels=True)"
in the create_data_gen_train in the train_network.py. Why not set the patch_size=(128,128,128) since the input shape is (128,128,128). Thank you!

**Comment by FabianIsensee** [comment]
I do this because rotations, scaling and elastic deformations are applied to the patches. By first sampling larger patches, then appyling the transformation and then cropping to 128x128x128 I prevent border artifacts to some extend.
Best,
Fabian

**Comment by yianzhongguo** [comment]
Well done，thank you very much!
