### ISSUE TITLE
Why reshape the y_true and y_pred in the function soft_dice_per_img_in_batch

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#24]
@FabianIsensee Hi, sir. I have one question about the function soft_dice_per_img_in_batch. I find that in the function the y_true and y_pred are all reshaped into (2, 2097152,4) before the computation of dice_scores. Why do this transform and why not use the original shape (2*128*128*128, 4). It looks that the reshaping operation do not impact the result of dice_scores.  Thank you!

**Comment by FabianIsensee** [comment]
Depends on how you do the tensor math. That version of the dice loss is quite old (it is the first version I ever wrote). There is plenty of ways to write that more elegantly. If you reformulate it to something else and the results are the same then that's fine, too ;-)

**Comment by yianzhongguo** [comment]
Thank you very much!
