### ISSUE TITLE
About the validation and test

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#25]
@FabianIsensee Hi, sir. I got into troubles again when I learned your code about validation and test. Especially, the function run_validation_mirroring in the validate_network.py was too hard to make it clear. Totally, I know it was designed to process predicted results but the detail was unclear. Could you help me describe the detailed functons of it  , thank you very much!

**Comment by FabianIsensee** [comment]
Hi,
I cannot describe all the details. I have an important review to do right now. The code should be self explanatory. The important bit is that I am doing test time data augmentation by mirroring along all axes. That may have looked confusing in the code.
Best,
Fabian

**Comment by yianzhongguo** [comment]
Thank you,sir！You could do your important things first. It is not urgent for me. It is that “”doing test time data augmentation by mirroring along all axes“” puzzled me. What is the principle？
