### ISSUE TITLE
Why to get prediction  this way

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#27]
@FabianIsensee Hi, sir.  I am puzzled for the line231 to line 268 in the utils_validation.py. It looks like these lines of code are used to get the prediction. But why the lines like "data_for_net = data_for_net[:, :, :, ::-1, :]" and "p = p[:, :, :, ::-1, ::-1]" appear. What is the meaning? Thank you very much!

**Comment by FabianIsensee** [comment]
This is the test time data augmentation via mirroring that I was talking about earlier :-)

**Comment by yianzhongguo** [comment]
Thank you！
