### ISSUE TITLE
Preprocessing: Bias field correction

### ISSUE THREAD

**Issue by akhanss** [MIC-DKFZ/BraTS2017#30]
Thanks a lot for the great and useful repo. We know that there is an issue called [bias field](http://brainsuite.org/processing/surfaceextraction/bfc/) in MR scans. I am just wondering how you have tackled the issue.

Regards,
Azam.

**Comment by FabianIsensee** [comment]
Dear Azam,
i don't tackle this issue at all. I use the BraTS data just like they 
were provided by the orzanizers.
Best,
Fabian

**Comment by akhanss** [comment]
Great to know that, thnx a lot for your prompt reply.
