### ISSUE TITLE
A question on the localization pathway

### ISSUE THREAD

**Issue by pykao** [MIC-DKFZ/BraTS2017#4]
Hello again,

From line 106,
```
l = norm_lrelu_upscale_conv_norm_lrelu(l, base_n_filter*8)
```
I assume it is the output of your first upscale and, this layer should then concatenate with the skip4 layer immediately.

But I noticed that you pass this layer through a 3D convolutional layer followed by batch normalization and leaky ReLU nonlinearity before concatenating with skip4. 
```
l = Conv3DLayer(l, base_n_filter*8, 1, 1, 'same', nonlinearity=linear, W=HeNormal(gain='relu'))
if do_norm:
    l = BatchNormLayer(l, axes=axes)
l = NonlinearityLayer(l, nonlin)

l = ConcatLayer((skip4, l), cropping=[None, None, 'center', 'center'])
```
You did not mention this layer in your paper. 
Can you explain what is the benefit to having this additional 3D convolutional layer?

Best,
Po-Yu

**Comment by FabianIsensee** [comment]
Dear Po-Yu,
these layers (line 108-111) should not be there. It is a bug that I only identified after the results were submitted. To be consistent with my submission to the challenge, I left it in. It does not make a noticeable difference in the results whether it is there or not.
Regards,
Fabian

**Comment by pykao** [comment]
Dear Fabian,
Thank you for your explanation!
Best,
Po-Yu
