### ISSUE TITLE
Trained model and feature visualization

### ISSUE THREAD

**Issue by samieti02** [MIC-DKFZ/BraTS2017#8]
Hello dear Sir,

First, I have a question, about feature visualization. How does the network visualizes the features? Is there already a method which do it? If yes, which method and how does it work in the code? If no, how can we integrate it in the tool, or which py files are better suitable for that. Can you give us some suggestions?

And second, is it possible to work with networks from your work, which are already trained? Because we dont have as much as data as in brats and wanted to test the data on a trained model, to see how good or bad the results are.

Thanks
Sami

**Comment by FabianIsensee** [comment]
Hi,
thank you for you interest in our work! This code was written in theano/lasagne and I have not touched this framework in a very long time. Thus I cannot help you with feature visualization. If you are familiar with theano you can define output variables that you can then extract during the forward pass.

About pretrained parameters: I can share them, but I am currently on vacation until the end of September. If it is urgent I recommend you download the BraTS data and train the model yourself. If you still need the parameters by the end of September please let me know and I will find a way to share them.

If you just need predictions form the model, you could just use our docker image: https://hub.docker.com/r/fabianisensee/brats2017_isensee/ It is easy to use, faster and has a better implementation of our model (it is based on pytorch and I reimplemented it from scratch).
You could also use our docker from this year: https://hub.docker.com/r/fabianisensee/isen2018/ It will give even better results.

Best,
Fabian
