### ISSUE TITLE
What is the brain_mask

### ISSUE THREAD

**Issue by yianzhongguo** [MIC-DKFZ/BraTS2017#9]
@FabianIsensee Hi, Isensee. I am reading your code and have learned a lot. But I do not make it clear when I find the line"brain_mask= (t1_img != t1_img[0, 0, 0]) & (t1c_img != t1c_img[0, 0, 0]) & (t2_img != t2_img[0, 0, 0]) & ( flair_img != flair_img[0, 0, 0])". What is the brain_mask, thank you!

**Comment by FabianIsensee** [comment]
Hi, the brain mask is just the mask of all nonzero voxels. The brats data is brain extracted meaning that the outside is all zeros. I am using that brain mask to do normalization within the brain region only and not having skewed mean and standard deviation due to background

**Comment by yianzhongguo** [comment]
@FabianIsensee Thank you! I have checked the original image of brats2017. I know it now the image[0,0,0] is 0 just like what you said.
